### ISSUE TITLE
Allow Images to load for localhost

### ISSUE THREAD

**Issue by tomstuder** [seancdavis/sapwood-classic#200]
Images do not load on sapwood projects locally.

![giphy 7](https://cloud.githubusercontent.com/assets/2223930/7204214/6f1d817e-e4ee-11e4-8271-bd5e2e812329.gif)

**Comment by seancdavis** [comment]
Up to v1.4.x, the settings are contained within `config/sapwood.yml` (or `config/taproot.yml`).

This setting:

``` yaml
dragonfly:
  secret: ''
```

Needs to match in development and production.

In future releases, this will likely not be an issue, since I'm in the process of sharing settings between environments.
