### ISSUE TITLE
Emails - Form Submit

### ISSUE THREAD

**Issue by tomstuder** [seancdavis/sapwood-classic#207]
## Enable email submissions to specified accounts within Admin/Site Settings
- Form enhancement
- Specify specific email accounts to receive an email from a form

**Example:**
- Drop-downs to select a subject or person
  - email would go to correct individuals
- If an option for **"Shop"** is selected in a form emails can be set up for the following:
  - **Individual email:** shop@website.com
  - **Ability to add multiples:** "shop@website.com, admin@website.com, judy@website.com, thatguy@website.com, souppacker@website.com"

**Comment by seancdavis** [comment]
Much done in [this commit](https://github.com/seancdavis/sapwood/commit/4c01db0b41a142af7f9dacec01df5582972389f2).

@hungrymedia: Please add the `ready` label when this is ready to be merged in.
