### ISSUE TITLE
Image Titles in Media Library

### ISSUE THREAD

**Issue by tomstuder** [seancdavis/sapwood-classic#231]
A certain e-commerce site we are working on has several product images that look similar.
- Having an Image Title Preview would assist Developers and Users in the admin select the correct image
- Having the Ability to add a custom title/name to the image in the Media Library would be even better

**Comment by seancdavis** [comment]
I’ve thought about this before, and I like this idea a lot, @tomstuder. I’m all about making the media library easier to use. This will be fairly straightforward to implement, so I’ll add it to v1.6.

**Comment by seancdavis** [comment]
Filenames were added to the media library in [this commit](https://github.com/seancdavis/sapwood/commit/b58056bffab605ac285a2f0db5a007c887d38691).

That's all I'm going to do for now. Like I mentioned in #232, I'm going to make some major changes with the media library in 2.0, so I wont be changing much until then.
