### ISSUE TITLE
Media - Bulk Media File Uploader

### ISSUE THREAD

**Issue by tomstuder** [seancdavis/sapwood-classic#232]
### Having the ability to bulk upload images into the media library
- Folder
- Drag and Drop Multiples

**Comment by seancdavis** [comment]
This is a really good idea, and it should eventually be added. I’m going to see how progress goes on v1.6 before applying this to a milestone, as it _could_ be time consuming.

**Comment by seancdavis** [comment]
We're going to take a different approach on file management as we look toward v2.0. Bulk upload _will_ be an option, though.
