### ISSUE TITLE
Infinitely nestable pages need to have view links

### ISSUE THREAD

**Issue by seancdavis** [seancdavis/sapwood-classic#24]
Pages are theoretically infinitely nestable, and that _seems_ to be working well. But there is no way to view child pages (i.e. the listing of that page's children).

**Comment by tomstuder** [comment]
Can you nest Grandparents and third cousins' brother-in-law twice removed?

**Comment by seancdavis** [comment]
Yes, but only in Kentucky.

**Comment by tomstuder** [comment]
No. Kentucky is for .scss - https://rubygems.org/gems/kentucky

**Comment by seancdavis** [comment]
This is working nicely, but it is confusing knowing how deeply-nested you are since the request path is not any indication. Therefore, have created #37 as an offshoot of this issue to make it easier to navigate.
