### ISSUE TITLE
Feature Reqeust - Guard - LiveReload

### ISSUE THREAD

**Issue by tomstuder** [seancdavis/sapwood-classic#241]
**Impressed by the auto/livereload of Middleman. I request this feature for sapwood**
https://github.com/guard/guard-livereload

**Comment by seancdavis** [comment]
Love that idea, @tomstuder! This applies more to the [Sapwood Developer](https://github.com/seancdavis/sapwood-developer) app, which is set to be released in late 2015. [I've added this as a feature request for that project](https://github.com/seancdavis/sapwood-developer/issues/7).
