### ISSUE TITLE
v1-stable is jacked

### ISSUE THREAD

**Issue by seancdavis** [seancdavis/sapwood-classic#43]
In production v1-stable can't precompile droid-sans-mono. Must be missing, although site in `master` branch can use.

Perhaps an issue of just waiting?

**Comment by tomstuder** [comment]
https://m.youtube.com/watch?v=nn2FB1P_Mn8

**Comment by seancdavis** [comment]
This is a case where the site was being developed in an environment using the `master` branch, while the production server was set at `v1-stable`. 

This isn't a bug, but is a consequence of using bleeding code in a development environment.
